app/build.gradle, app/src/main/java/org/metabrainz/mobile/adapter/list/ArtistReleaseAdapter.java, app/src/main/java/org/metabrainz/mobile/api/webservice/LookupService.java, app/src/main/java/org/metabrainz/mobile/api/webservice/MusicBrainzServiceGenerator.java, app/src/main/java/org/metabrainz/mobile/repository/LookupRepository.java, app/src/main/java/org/metabrainz/mobile/viewmodel/ArtistViewModel.java
Fix wrong display of cover art when recycler view is fast scrolled.
=> Fix cover art

app/src/main/AndroidManifest.xml, app/src/main/java/org/metabrainz/mobile/api/webservice/Constants.java, app/src/main/java/org/metabrainz/mobile/data/repository/LabelLookupRepository.java, app/src/main/java/org/metabrainz/mobile/data/sources/api/entities/mbentity/Label.java, app/src/main/java/org/metabrainz/mobile/presentation/SearchFragment.java, app/src/main/java/org/metabrainz/mobile/presentation/features/artist/ArtistReleaseAdapter.java, app/src/main/java/org/metabrainz/mobile/presentation/features/artist/ArtistReleasesFragment.java, app/src/main/java/org/metabrainz/mobile/presentation/features/label/LabelActivity.java, app/src/main/java/org/metabrainz/mobile/presentation/features/label/LabelInfoFragment.java, app/src/main/java/org/metabrainz/mobile/presentation/features/label/LabelReleaseAdapter.java, app/src/main/java/org/metabrainz/mobile/presentation/features/label/LabelReleasesFragment.java, app/src/main/java/org/metabrainz/mobile/presentation/features/label/LabelViewModel.java, app/src/main/java/org/metabrainz/mobile/presentation/features/search/SearchActivity.java, app/src/main/java/org/metabrainz/mobile/presentation/features/search/SearchAdapterLabel.java, app/src/main/res/layout/activity_label.xml, app/src/main/res/layout/card_release_item.xml, app/src/main/res/layout/fragment_label_info.xml, app/src/main/res/layout/fragment_label_releases.xml, app/src/main/res/values/strings.xml
Add label info pages with list of releases on a label and details of the label.
=> Add label details pages.

app/src/main/java/org/metabrainz/mobile/data/repository/LookupRepository.java, app/src/main/java/org/metabrainz/mobile/data/repository/TaggerRepository.java, app/src/main/java/org/metabrainz/mobile/presentation/features/tagger/TaggerFragment2.kt, app/src/main/java/org/metabrainz/mobile/presentation/features/tagger/TaggerViewModel.kt
=> Fixes before 2nd release

app/src/main/AndroidManifest.xml, app/src/main/java/org/metabrainz/mobile/presentation/features/tagger/DirectoryPicker.kt, app/src/main/java/org/metabrainz/mobile/presentation/features/tagger/TaggerFragment2.kt, app/src/main/java/org/metabrainz/mobile/presentation/features/tagger/TaggerViewModel.kt
- Added the queries tag in the Manifest to tackle the issues while opening the Directories.
=> Tagger Fix

app/src/main/AndroidManifest.xml, app/src/main/java/org/metabrainz/mobile/presentation/features/release/ReleaseActivity.kt, app/src/main/java/org/metabrainz/mobile/presentation/features/tagger/DirectoryPicker.kt, app/src/main/java/org/metabrainz/mobile/presentation/features/tagger/TaggerFragment2.kt, app/src/main/java/org/metabrainz/mobile/presentation/features/tagger/TaggerViewModel.kt, app/src/main/java/org/metabrainz/mobile/util/TaggerUtils.kt, app/src/main/res/layout/fragment_directory_picker.xml, app/src/main/res/layout/fragment_tagger.xml, app/src/main/res/layout/fragment_tagger2.xml
- Moved the Overwrite Tags Button to bottom and fixed window input mode in Manifest
- Added Lottie Animation and changed the layout.
- Fixed the visibility criteria
- Managed colors in a better way
=> Tagger update

app/src/main/assets/about.html
=> About Section Updates

Readme.md
This is a great motivation to keep track of the response the app is getting on the playstore!
=> Added play badges

Readme.md
We have a lot of features which can take off the app to a whole new dimension!
=> Readme Updates

app/src/main/java/org/metabrainz/android/presentation/features/base/LookupViewModel.kt, app/src/main/java/org/metabrainz/android/presentation/features/label/LabelViewModel.kt, app/src/test/java/org/metabrainz/android/CollectionViewModelTest.kt, app/src/test/java/org/metabrainz/android/LookupViewModelTest.kt
=> Tests fixed

app/src/main/java/org/metabrainz/android/data/sources/api/MusicBrainzServiceGenerator.kt, app/src/main/java/org/metabrainz/android/presentation/features/login/LoginActivity.kt
=> Change redirect uri and update credentials

app/src/main/java/org/metabrainz/android/presentation/features/search/SearchActivity.kt, app/src/main/res/layout/activity_search.xml
- Added a toast to check the internet of searches without the internet being on.
- Added loading and result not found animation in search feature.
=> search-feature-fixes

app/build.gradle, app/src/main/java/org/metabrainz/android/presentation/features/adapters/BlogAdapter.kt, app/src/main/java/org/metabrainz/android/presentation/features/newsbrainz/NewsBrainzActivity.kt, build.gradle
This feature integrated the Share library and allows us to share text and media very easily across all platforms.
=> Share functionality added

app/src/main/java/org/metabrainz/android/presentation/features/search/SearchActivity.kt, app/src/main/java/org/metabrainz/android/presentation/features/search/SearchPagingSource.kt, app/src/main/java/org/metabrainz/android/presentation/features/search/SearchViewModel.kt, app/src/main/res/layout/activity_search.xml, app/src/main/res/layout/dropdown_page.xml
- Instead of pagination, search results will come on different pages.
- Added buttons to navigate between pages.
- Added menu to reach any particular page.
- Prevents too many requests to be made in a short time.
Screenshots attached:
=> search-feature-improved

app/build.gradle, app/src/main/AndroidManifest.xml, app/src/main/java/org/metabrainz/android/presentation/features/barcode/BarcodeActivity.kt, app/src/main/java/org/metabrainz/android/presentation/features/dashboard/DashboardActivity.kt, app/src/main/java/org/metabrainz/android/presentation/features/login/LoginActivity.kt, app/src/main/java/org/metabrainz/android/presentation/features/search/SearchActivity.kt, app/src/main/res/layout/activity_barcode.xml, app/src/main/res/layout/activity_dashboard.xml, app/src/main/res/layout/activity_search.xml, app/src/main/res/values-night/styles.xml, app/src/main/res/values/styles.xml
The UI has been updated to accommodate new features to the app.
=> Move Barcode Scanner to Search and Improve UX

app/build.gradle, app/src/main/java/org/metabrainz/android/presentation/features/listens/ListensActivity.kt
- We witnessed the app crashing upon resuming the activity. Also, the layout seemed incorrect when no active song was playing. Hence these fixes have been made.
=> Fix the Spotify SDK implementation

app/build.gradle, app/src/main/java/org/metabrainz/android/presentation/UserPreferences.kt, app/src/main/java/org/metabrainz/android/presentation/features/dashboard/DashboardActivity.kt, app/src/main/java/org/metabrainz/android/presentation/features/listens/ListensActivity.kt, build.gradle
- Some users had reported that the onboarding wasn't moving forward and upon investing, I figured that we need to fix the way we locally save the boolean whether the onboarding has been done or not.
- The client id has been taken from Rob and the official credentials have been added,
=> Fix onboarding issue and update the client id for Spotify SDK

app/src/main/java/org/metabrainz/android/presentation/features/brainzplayer/services/BrainzPlayerService.kt, app/src/main/java/org/metabrainz/android/presentation/features/brainzplayer/services/callback/BrainzPlayerEventListener.kt, app/src/main/java/org/metabrainz/android/presentation/features/brainzplayer/services/callback/BrainzPlayerNotificationListener.kt, app/src/main/java/org/metabrainz/android/presentation/features/brainzplayer/services/callback/MusicPlaybackPreparer.kt, app/src/main/java/org/metabrainz/android/presentation/features/brainzplayer/services/notification/BrainzPlayerNotificationManager.kt, app/src/main/java/org/metabrainz/android/util/BrainzPlayerExtensions.kt, app/src/main/res/values/strings.xml
This pr targets:
- Service lifecycle created, added service connection.
- Added callbacks for playback,notification and player state
- Added notification manager using exoplayer's PlayerNotificationManager.
- Some extension functions for playback state and dealing with media metadata
=> Service completion, Service callbacks and notification stuff created, basic service setup complete

app/build.gradle, app/src/main/java/org/metabrainz/android/data/di/brainzplayer/ServiceModule.kt, app/src/main/java/org/metabrainz/android/data/di/brainzplayer/SongRepositoryModule.kt, app/src/main/java/org/metabrainz/android/data/repository/SongRepositoryImpl.kt, app/src/main/java/org/metabrainz/android/data/sources/brainzplayer/Song.kt, app/src/main/java/org/metabrainz/android/presentation/components/BottomNavigationBar.kt, app/src/main/java/org/metabrainz/android/presentation/features/brainzplayer/musicsource/LocalMusicSource.kt, app/src/main/java/org/metabrainz/android/presentation/features/brainzplayer/services/BrainzPlayerServiceConnection.kt, app/src/main/java/org/metabrainz/android/presentation/features/brainzplayer/services/notification/BrainzPlayerNotificationManager.kt, app/src/main/java/org/metabrainz/android/presentation/features/brainzplayer/ui/BrainzPlayerViewModel.kt, app/src/main/java/org/metabrainz/android/presentation/features/brainzplayer/ui/components/Buttons.kt, app/src/main/java/org/metabrainz/android/presentation/features/brainzplayer/ui/components/MarqueeText.kt, app/src/main/java/org/metabrainz/android/presentation/features/brainzplayer/ui/components/SeekBar.kt, app/src/main/java/org/metabrainz/android/presentation/features/dashboard/DashboardActivity.kt, app/src/main/java/org/metabrainz/android/presentation/features/dashboard/DashboardBackdropBackLayerContent.kt, app/src/main/java/org/metabrainz/android/util/BrainzPlayerExtensions.kt
In this PR, few UI updates were made:
- Notification controls for music playback
- Viewpager for songs scrolling in bottom bar
- A backdrop was implemented for further UI additions for bp
https://user-images.githubusercontent.com/75999921/177485116-a430eca8-2aa5-45c4-a05e-31b0c5a030ba.mp4
new update:
https://user-images.githubusercontent.com/75999921/178151914-63518a3c-e72b-46a7-b676-e6eea779fe4a.mp4
=> Added initial UI changes

app/build.gradle, app/src/main/AndroidManifest.xml, app/src/main/java/org/metabrainz/android/presentation/components/BottomNavigationBar.kt, app/src/main/java/org/metabrainz/android/presentation/components/FlingBehavior.kt, app/src/main/java/org/metabrainz/android/presentation/features/brainzplayer/services/BrainzPlayerServiceConnection.kt, app/src/main/java/org/metabrainz/android/presentation/features/brainzplayer/ui/BrainzPlayerActivity.kt, app/src/main/java/org/metabrainz/android/presentation/features/brainzplayer/ui/BrainzPlayerBackDropScreen.kt, app/src/main/java/org/metabrainz/android/presentation/features/brainzplayer/ui/BrainzPlayerViewModel.kt, app/src/main/java/org/metabrainz/android/presentation/features/brainzplayer/ui/components/Buttons.kt, app/src/main/java/org/metabrainz/android/presentation/features/brainzplayer/ui/components/SeekBar.kt, app/src/main/java/org/metabrainz/android/presentation/features/dashboard/DashboardActivity.kt, app/src/main/java/org/metabrainz/android/presentation/features/dashboard/DashboardBackdropBackLayerContent.kt, app/src/main/java/org/metabrainz/android/presentation/features/navigation/NavigationItem.kt, app/src/main/res/drawable/ic_erroralbumart.xml, app/src/main/res/drawable/ic_liked.xml, app/src/main/res/drawable/ic_not_liked.xml, app/src/main/res/values-night/colors.xml, app/src/main/res/values/colors.xml, app/src/main/res/values/strings.xml
this commit targets:
- Fresh UI changes ( including new bottom navbar for brainzplayer activity, color changes and icons)
- A brainzplayer activity
[<img src="https://drive.google.com/uc?export=view&id=1VB_i8CDBsDv19Mt1xyxO7SB3oMcZ8nsR" width="250"/>](image.png)
[<img src="https://drive.google.com/uc?export=view&id=1V0Tlo-HcFxrQJd46IU3pC9lHph4vHH37" width="250"/>](image.png)
- A brainzplayer screen
[<img src="https://drive.google.com/uc?export=view&id=12Ea2KjsWUa4QkTx5L24WYSnX5jGVC-z4" width="250"/>](image.png)
- Changes in BP bottom view pager
[<img src="https://drive.google.com/uc?export=view&id=1VEnI2_MiLo_Au_pIMt_s8zDM-xKTgfnY" width="250"/>](image.png)
[<img src="https://drive.google.com/uc?export=view&id=1VJd1N6u4vDZq9BTSPlVX65iKDMTbfU2-" width="250"/>](image.png)
=> Added UI changes

app/src/main/AndroidManifest.xml, app/src/main/java/org/metabrainz/android/presentation/features/dashboard/DashboardActivity.kt
fixes no permissions being asked in api level 33
=> ticket mobile-79 fix: granual permissions for api 33

.github/workflows/android-lint.yml, .github/workflows/android.yml, app/build.gradle, app/src/main/AndroidManifest.xml, app/src/main/java/org/metabrainz/android/application/App.kt, app/src/main/java/org/metabrainz/android/ui/screens/onboarding/FeaturesActivity.kt, app/src/main/java/org/metabrainz/android/ui/screens/settings/SettingsActivity.kt, app/src/main/java/org/metabrainz/android/ui/screens/settings/SettingsFragment.kt, app/src/main/java/org/metabrainz/android/util/UserPreferences.kt, app/src/main/res/xml/preferences.xml, build.gradle, fastlane/metadata/android/en-US/changelogs/55.txt, gradle.properties, gradle/wrapper/gradle-wrapper.properties
- Listens service will only be available via the LB app now.
- Dependencies updated.
=> Remove Listens Service and Bump Dependencies

Readme.md
Exhaustivity verified thanks to:
```bash
grep -r ',[^ ]' --include=*.md
```
=> Add a missing space to `Readme.md`
